version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: epicure-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: epicure-server
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/epicure?authSource=admin
      - NODE_ENV=development
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: epicure-client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - server

volumes:
  mongodb_data: 