import { ReactComponent as Hamburger } from "./HAMBURGER.svg";
import { ReactComponent as Arrow } from "./arrow.svg";
import { ReactComponent as Bag } from "./bag.svg";
import { ReactComponent as Clock } from "./clock.svg";
import { ReactComponent as Lock } from "./lock.svg";
import { ReactComponent as Search } from "./search.svg";
import { ReactComponent as Shekel } from "./shekel.svg";
import { ReactComponent as User } from "./user.svg";
import { ReactComponent as X_dark } from "./x-dark.svg";
import { ReactComponent as X_white } from "./x_white.svg";
import { ReactComponent as VeganBig } from "./veganBig.svg";
import { ReactComponent as VeganSmall } from "./veganSmall.svg";
import { ReactComponent as VegetarianBig } from "./VegetarianBig.svg";
import { ReactComponent as VegetarianSmall } from "./vegetarianSmall.svg";
import { ReactComponent as SpicyBig } from "./spicyBig.svg";
import { ReactComponent as SpicySmall } from "./spicySmall.svg";
import { ReactComponent as Logo } from "./about-logo@3x 1.svg";
import { ReactComponent as FullStar } from "./Star 1.svg";
import { ReactComponent as EmptyStar } from "./Star 5.svg";
import { ReactComponent as CheckOff } from "./checkOff.svg";
import { ReactComponent as CheckOn } from "./checkOn.svg";
import { ReactComponent as CheckCircleOff } from "./checkCircleOff.svg";
import { ReactComponent as CheckCircleOn } from "./checkCircleOn.svg";
import { ReactComponent as ArrowDown } from "./arrowDown.svg";
import { ReactComponent as Plus } from "./plus.svg";
import { ReactComponent as Minus } from "./minus.svg";
import { ReactComponent as Vector } from "./vector.svg";
import { ActiveBag } from "./ActiveBag";

export { Hamburger, Arrow, Bag, Vector, Clock, Lock, Search, Shekel, User, X_dark, X_white, Logo, VeganBig, VeganSmall, VegetarianBig, VegetarianSmall, SpicyBig, SpicySmall, FullStar, EmptyStar, ArrowDown, ActiveBag, CheckOff, CheckOn, CheckCircleOff, CheckCircleOn, Plus, Minus };
